version: "3"

services:
  postgresql:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=marshalexamples
      - POSTGRES_USER=marshalexamples
      - POSTGRES_DB=marshalexamples
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "6543:5432"
    restart: unless-stopped

volumes:
  pgdata: # named volumes can be managed easier using docker-compose
